// src/components/common/Icon.jsx
import React from 'react';
import {
  Plane,
  PlaneTakeoff,
  PlaneLanding,
  Home,
  CheckCircle2,
  CheckCheck,
  Check,
  HelpCircle,
  Info,
  AlertCircle,
  AlertTriangle,
  Star,
  MessageSquare,
  MessagesSquare,
  Mail,
  Send,
  Phone,
  MapPin,
  Menu,
  X,
  ArrowRight,
  ArrowLeft,
  ArrowUpDown,
  ArrowRightLeft,
  Calendar,
  CalendarDays,
  CalendarRange,
  Users,
  User,
  UserCheck,
  UserPlus,
  Lock,
  Shield,
  ShieldCheck,
  CreditCard,
  Search,
  Sparkles,
  Ticket,
  Download,
  Printer,
  Share2,
  Copy,
  Clock,
  Globe,
  Building,
  Building2,
  Compass,
  Tag,
  Gift,
  DollarSign,
  Percent,
  Loader2,
  RefreshCw,
  ChevronDown,
  ChevronUp,
  ChevronRight,
  ChevronLeft,
  Luggage,
  Briefcase,
  FileText,
  FileCheck,
  ExternalLink,
  Eye,
  EyeOff,
  Heart,
  Smile,
  Edit,
  Bell,
  Navigation,
  MousePointer,
  Award,
  Zap,
  Coffee,
  Wifi,
  ShieldAlert,
  ThumbsUp,
  Headphones,
  CheckSquare
} from 'lucide-react';

const ICON_MAP = {
  // Navigation & General
  'home': Home,
  'fa-home': Home,
  'verify': CheckCheck,
  'fa-check-double': CheckCheck,
  'check-double': CheckCheck,
  'why-us': HelpCircle,
  'question-circle': HelpCircle,
  'fa-question-circle': HelpCircle,
  'fa-circle-question': HelpCircle,
  'testimonials': Star,
  'star': Star,
  'fa-star': Star,
  'fa-star-half-alt': Star,
  'fa-comments': MessagesSquare,
  'comments': MessagesSquare,
  'comment': MessageSquare,
  'fa-comment': MessageSquare,
  'fa-envelope': Mail,
  'envelope': Mail,
  'mail': Mail,
  'bars': Menu,
  'fa-bars': Menu,
  'times': X,
  'fa-times': X,
  'close': X,
  'x': X,

  // Planes & Aviation
  'plane': Plane,
  'fa-plane': Plane,
  'plane-departure': PlaneTakeoff,
  'fa-plane-departure': PlaneTakeoff,
  'plane-arrival': PlaneLanding,
  'fa-plane-arrival': PlaneLanding,
  'route': Compass,
  'fa-route': Compass,
  'ticket': Ticket,
  'fa-ticket-alt': Ticket,
  'fa-ticket': Ticket,
  'luggage': Luggage,
  'fa-suitcase': Luggage,
  'fa-suitcase-rolling': Luggage,
  'briefcase': Briefcase,
  'fa-briefcase': Briefcase,
  'airport': Building2,
  'fa-building': Building,
  'globe': Globe,
  'fa-globe': Globe,
  'fa-globe-americas': Globe,
  'compass': Compass,
  'fa-compass': Compass,

  // Travel / Booking Steps
  'exchange-alt': ArrowRightLeft,
  'fa-exchange-alt': ArrowRightLeft,
  'arrow-right': ArrowRight,
  'fa-arrow-right': ArrowRight,
  'arrow-left': ArrowLeft,
  'fa-arrow-left': ArrowLeft,
  'arrow-up-down': ArrowUpDown,
  'fa-arrows-alt-v': ArrowUpDown,
  'calendar': Calendar,
  'fa-calendar': Calendar,
  'fa-calendar-alt': CalendarDays,
  'fa-calendar-day': Calendar,
  'fa-calendar-week': CalendarRange,
  'fa-calendar-times': Calendar,
  'user': User,
  'fa-user': User,
  'fa-user-friends': Users,
  'users': Users,
  'fa-user-plus': UserPlus,
  'fa-user-check': UserCheck,
  'fa-passport': FileCheck,
  'passport': FileCheck,

  // Security / Payment
  'lock': Lock,
  'fa-lock': Lock,
  'shield': Shield,
  'fa-shield': Shield,
  'fa-shield-alt': ShieldCheck,
  'fa-shield-halved': ShieldCheck,
  'credit-card': CreditCard,
  'fa-credit-card': CreditCard,
  'fa-cc-visa': CreditCard,
  'fa-cc-mastercard': CreditCard,
  'dollar': DollarSign,
  'fa-dollar-sign': DollarSign,
  'tag': Tag,
  'fa-tag': Tag,
  'fa-tags': Tag,
  'gift': Gift,
  'fa-gift': Gift,
  'percent': Percent,
  'fa-percent': Percent,

  // Actions & Utilities
  'search': Search,
  'fa-search': Search,
  'sparkles': Sparkles,
  'fa-sparkles': Sparkles,
  'fa-magic': Sparkles,
  'download': Download,
  'fa-download': Download,
  'print': Printer,
  'fa-print': Printer,
  'share': Share2,
  'fa-share-alt': Share2,
  'copy': Copy,
  'fa-copy': Copy,
  'edit': Edit,
  'fa-edit': Edit,
  'fa-pen': Edit,
  'bell': Bell,
  'fa-bell': Bell,
  'mouse-pointer': MousePointer,
  'fa-mouse-pointer': MousePointer,
  'navigation': Navigation,
  'fa-location-arrow': Navigation,
  'map-pin': MapPin,
  'fa-map-marker-alt': MapPin,
  'phone': Phone,
  'fa-phone': Phone,
  'fa-phone-alt': Phone,
  'clock': Clock,
  'fa-clock': Clock,
  'check': Check,
  'fa-check': Check,
  'fa-check-circle': CheckCircle2,
  'check-circle': CheckCircle2,
  'fa-exclamation-circle': AlertCircle,
  'fa-exclamation-triangle': AlertTriangle,
  'fa-info-circle': Info,
  'info': Info,
  'spinner': Loader2,
  'fa-spinner': Loader2,
  'refresh': RefreshCw,
  'fa-sync': RefreshCw,
  'fa-sync-alt': RefreshCw,
  'chevron-down': ChevronDown,
  'fa-chevron-down': ChevronDown,
  'chevron-up': ChevronUp,
  'fa-chevron-up': ChevronUp,
  'chevron-right': ChevronRight,
  'fa-chevron-right': ChevronRight,
  'chevron-left': ChevronLeft,
  'fa-chevron-left': ChevronLeft,
  'eye': Eye,
  'fa-eye': Eye,
  'eye-off': EyeOff,
  'fa-eye-slash': EyeOff,
  'award': Award,
  'fa-award': Award,
  'zap': Zap,
  'fa-bolt': Zap,
  'wifi': Wifi,
  'fa-wifi': Wifi,
  'coffee': Coffee,
  'fa-coffee': Coffee,
  'thumbs-up': ThumbsUp,
  'fa-thumbs-up': ThumbsUp,
  'headphones': Headphones,
  'fa-headset': Headphones,
  'check-square': CheckSquare,
  'fa-check-square': CheckSquare
};

export const Icon = ({ 
  name, 
  className = '', 
  size = 18, 
  color, 
  style = {}, 
  spin = false,
  ...props 
}) => {
  // Determine icon key from name or className
  let iconKey = (name || '').toLowerCase().trim();
  
  if (!iconKey && className) {
    const classes = className.split(/\s+/);
    for (const cls of classes) {
      if (cls.startsWith('fa-') && cls !== 'fa-spin' && cls !== 'fa-2x' && cls !== 'fa-3x' && cls !== 'fa-lg' && cls !== 'fa-fw') {
        iconKey = cls;
        break;
      }
    }
  }

  // Clean prefixes
  const normalizedKey = iconKey.replace(/^fa[srbd]?\s+/, '').replace(/^fa-/, '');
  const Component = ICON_MAP[iconKey] || ICON_MAP[`fa-${normalizedKey}`] || ICON_MAP[normalizedKey] || Sparkles;

  const isSpinning = spin || className.includes('fa-spin') || className.includes('animate-spin') || iconKey.includes('spinner');

  return (
    <Component 
      size={size} 
      color={color} 
      className={`icon-svg inline-block shrink-0 ${isSpinning ? 'animate-spin' : ''} ${className}`}
      style={{
        display: 'inline-block',
        verticalAlign: 'middle',
        ...style
      }}
      aria-hidden="true"
      {...props}
    />
  );
};

export default Icon;
